import json

##########
# This class is meant for doc Upload, all supported ETL fn's / tools / methods 
# should be added here 
#
#
##########


class UploadService(object):
    def __init__(self,session): #allow for manual JWT input if we want to have JWTs generated by admin console in the future
        super(UploadService, self).__init__()
        self._session = session
        self.urlResource = '/api/v20/ingest/document' #url extension for search

    def docUpload(self,data):
        #EXAMPLE DATA INPUT BELOW
        '''
        data = {
            "title": "Testing",
            "text": "In the context of language models and AI, a multi-agent system involves multiple independent actors, each powered by language models, collaborating in a specific way.",
            "date": "2024-07-01T20:30:12.435Z",
            "language": "en",
            "source_meta": {
                "data_source_name": "news",
                "source_name": "Medium",
                "vendor_id": "medium"
                }
            }

        '''

        metadata = {                   #MUST INCLUDE tags & operation METADATA FIELDS FOR LOG TRACKING
            'tags' : ['Upload'],
            'operation' : 'docUpload'
        }
        return self._session.post(metadata,self.urlResource,data = json.dumps(data))

